export const initialValues = {
    coord: { lon: 0, lat: 0 },
    weather: [
        { id: 0, main: "", description: "", icon: "" },
    ],
    base: "",
    main: {
        temp: 0,
        feels_like: 0,
        temp_min: 0,
        temp_max: 0,
        pressure: 0,
        humidity: 0,
    },
    visibility: 0,
    wind: { speed: 0, deg: 0 },
    clouds: { all: 0 },
    dt: 0,
    sys: {
        type: 0,
        id: 0,
        country: "",
        sunrise: 0,
        sunset: 0,
    },
    timezone: 0,
    id: 0,
    name: "",
    cod: 0,
};

export const futureInitialValues = {
    lat: 0,
    lon: 0,
    timezone: "",
    timezone_offset: 0,
    current: {
        dt: 0,
        sunrise: 0,
        sunset: 0,
        temp: 0,
        feels_like: 0,
        pressure: 0,
        humidity: 0,
        dew_point: 0,
        uvi: 0,
        clouds: 0,
        visibility: 0,
        wind_speed: 0,
        wind_deg: 0,
        wind_gust: 0,
        weather: [{ id: 0, main: "", description: "", icon: "" }],
    },
    daily: [
        {
            dt: 0,
            sunrise: 0,
            sunset: 0,
            moonrise: 0,
            moonset: 0,
            moon_phase: 0,
            temp: {
                day: 0,
                min: 0,
                max: 0,
                night: 0,
                eve: 0,
                morn: 0,
            },
            feels_like: { day: 0, night: 0, eve: 0, morn: 0 },
            pressure: 0,
            humidity: 0,
            dew_point: 0,
            wind_speed: 0,
            wind_deg: 0,
            wind_gust: 0,
            weather: [{ id: 500, main: "", description: "", icon: "" }],
            clouds: 0,
            pop: 0,
            rain: 0,
            uvi: 0,
        },
    ],
};